### ISSUE TITLE
GetMultiChannelScalingTileComposite option

### ISSUE THREAD

**Issue by tryphoncosinus** [ptahmose/MEXlibCZI#1]
Hello,

MEXlibCZI is a very useful program.

h = MEXlibCZI('Open','/Data/MyFile.czi') % Working command
b1=MEXlibCZI('GetMultiChannelScalingTileComposite',h,[0 0 139758 103021],'',0.005); % This does not work
I get this message : One or more output arguments not assigned during call to "MEXlibCZI".

Other MexlibCZI options works fine.

Anything to do ?

Thnak you!

My config:
{'VersionString'         }    {'0.1.0-alpha'                             }
    {'LibraryName'           }    {'MEXlibCZI'                               }
    {'CompilerIdentification'}    {'GNU 9.3.0'                               }
    {'libCZIVersion'         }    {'0.45'                                    }
    {'libCZIRepoUrl'         }    {'https://github.com/ptahmose/libCZI.git'  }
    {'libCZIRepoBranch'      }    {'master'                                  }
    {'libCZIRepoTag'         }    {'5bb2d5402a859f1ae5cf09459c2e982dec2533b2'}

MEXlibCZI downloaded from 20211015.2 link
Ubuntu 20.04
MATLAB 2021b

**Comment by pthamose** [comment]
Thanks for trying "MEXlibCZI". 
Hmm, what could wrong in your case - the third argument ("plane coordinate") must uniquely identify a plane, and what coordinates must be given here depends on the CZI-document (c.f. [here](https://github.com/ptahmose/MEXlibCZI/wiki/Commands#getmultichannelscalingtilecomposite) and [here](https://ptahmose.github.io/libCZI-doc/naczircmd.html), ch. "command ChannelComposite"). So e.g. if the CZI contains a Z-stack, you have to specify the Z-index here (e.g. 'Z5'). This can only be an empty string if the document contains only one plane.
To check for this, running 

info=MEXlibCZI('GetInfo',h)

should be helpful, then inspect the property 'dimBounds"
![image](https://user-images.githubusercontent.com/4881321/145118122-8d12fffb-63e6-4b73-93c7-ad71e60f602d.png)

Hope this helps, otherwise - if you can provide me the CZI you are testing with, I'll try to have a look.

**Comment by tryphoncosinus** [comment]
Clearly I misunderstood this third argument. I tried and it works as it should. Thank you for this explanation!

**Comment by ptahmose** [comment]
I prepare a new [build ](https://github.com/ptahmose/MEXlibCZI/releases/tag/20211220.3) which should give a more reasonable and useful error-message for this case. Also, includes latest updates from upstream.
